[pytest]
testpaths = tests backend
norecursedirs = chandrayaan2-crossmatch node_modules lunar-frontend .git .cache .pytest_cache scratch
addopts = --ignore=chandrayaan2-crossmatch
filterwarnings =
    ignore::DeprecationWarning
    ignore::rasterio.errors.NotGeoreferencedWarning
